### ISSUE TITLE
Crash on request timeout

### ISSUE THREAD

**Issue by wfriesen** [marshl/Lobster#103] opened 2016-09-19 00:19 UTC
After connecting normally, I saw the following error appear while trying to pull an XSD:

```
2016-09-19 10:12:36.402 [ERROR]: Connection to Oracle failed: Connection request timed out
2016-09-19 10:12:36.457 [ERROR]: Unhandled Exception LobsterModel.ConnectToDatabaseException: Failed to open connection: Connection request timed out ---> Oracle.ManagedDataAccess.Client.OracleException: Connection request timed out
   at OracleInternal.ConnectionPool.PoolManager`3.Get(ConnectionString csWithDiffOrNewPwd, Boolean bGetForApp, String affinityInstanceName, Boolean bForceMatch)
   at OracleInternal.ConnectionPool.OraclePoolManager.Get(ConnectionString csWithNewPassword, Boolean bGetForApp, String affinityInstanceName, Boolean bForceMatch)
   at OracleInternal.ConnectionPool.OracleConnectionDispenser`3.Get(ConnectionString cs, PM conPM, ConnectionString pmCS, SecureString securedPassword, SecureString securedProxyPassword)
   at Oracle.ManagedDataAccess.Client.OracleConnection.Open()
   at LobsterModel.Model.OpenConnection(DatabaseConfig config, SecureString password) in C:\Users\Fivium\Projects\Lobster\LobsterModel\Model.cs:line 485
   --- End of inner exception stack trace ---
   at LobsterModel.Model.OpenConnection(DatabaseConfig config, SecureString password) in C:\Users\Fivium\Projects\Lobster\LobsterModel\Model.cs:line 492
   at LobsterModel.Model.SendDownloadClobDataToFileMessage(DatabaseConnection databaseConnection, DBClobFile databaseFile) in C:\Users\Fivium\Projects\Lobster\LobsterModel\Model.cs:line 168
   at LobsterWpf.MainWindow.PullButton_Click(Object sender, RoutedEventArgs e) in C:\Users\Fivium\Projects\Lobster\LobsterWpf\Views\MainWindow.xaml.cs:line 338
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at LobsterWpf.App.Main() in C:\Users\Fivium\Projects\Lobster\LobsterWpf\obj\Release\App.g.cs:line 0
2016-09-19 10:12:36.458 [INFO]: Lobster Stopped
```

**Comment by marshl** [comment] 2016-09-19 14:10
Duplicate of #99

**Closed by marshl** 2016-09-19 14:10 UTC
